name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install
        run: |
          npm install
          npm run postinstall

      - name: Publish windows releases
        env:
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'windows-latest'
        run: |
          npm run package:win

      - name: Publish Mac releases
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        if: matrix.os == 'macos-latest'
        run: |
          npm run package:mac
